In [8]:
import sys
import numpy as np
import matplotlib.pyplot as plt

In [9]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3
output= inputs[0]* weights[0] +inputs[1]* weights[1]+ inputs[2]* weights[2] + bias
print(output)

35.7


In [14]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2
output= inputs[0]* weights[0] +inputs[1]* weights[1]+ inputs[2]* weights[2] + inputs[3]* weights[3] + bias
print(output)

4.8


4 inputs 3 neurons

In [16]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]
bias1=2
bias2=3
bias3=0.5
output= [inputs[0]* weights1[0] +inputs[1]* weights1[1]+ inputs[2]* weights1[2] + inputs[3]* weights1[3] + bias1,
         inputs[0]* weights2[0] +inputs[1]* weights2[1]+ inputs[2]* weights2[2] + inputs[3]* weights2[3] + bias2,
         inputs[0]* weights3[0] +inputs[1]* weights3[1]+ inputs[2]* weights3[2] + inputs[3]* weights3[3] + bias3]
print(output)

[4.8, 1.21, 2.385]


In [36]:
output=[]

inputs=[1,2,3,2.5]
# weights1=[0.2,0.8,-0.5,1.0]
# weights2=[0.5,-0.91,0.26,-0.5]
# weights3=[-0.26,-0.27,0.17,0.87]
weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

for weight in range(len(weights)):
        total=0
        for i in range(len(inputs)):
            total += inputs[i] * weights[weight][i]
        total+=bias[weight]
        output.append(total)
print(output)

[4.8, 1.21, 2.385]


In [ ]:
weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]


In [29]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

output = []

for n in range(len(weights)):   # loop over each neuron
    total = 0
    for i in range(len(inputs)):
        total += inputs[i] * weights[n][i]   # multiply and sum
    total += biases[n]   # add bias for that neuron
    output.append(total)

print(output)


[4.8, 1.21, 2.385]


In [1]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2, 3, 0.5]

In [ ]:
## by using dot product

In [6]:
import numpy as np
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias=2
output=np.dot(weights,inputs)+ bias
print(output)

4.8


In [21]:
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases=[2,3,0.5]
output=np.dot(weights,inputs)+ biases
print(output)

[4.8   1.21  2.385]


for batch of inputs


In [11]:
inputs=[[1,2,3,2.5],
        [2.0,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]
weigths=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
output=np.dot(inputs,np.array(weights).T) + biases
print(output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [22]:
inputs=[[1,2,3,2.5],
        [2.0,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]
weigths=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
##layer 2
weights2=[[0.1,-0.14, 0.5],
         [-0.5, 0.12, -0.33],
         [-0.44, 0.73, -0.13]]
biases2=[-1,2,-0.5]

layer1_output=np.dot(inputs,np.array(weights).T) + biases  ##output of layer 1 becomes the input for layer 2
layer2_output=np.dot(layer1_output, np.array(weights2).T) + biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


using class concenpt

In [44]:
import numpy as np
np.random.seed(0)
X=[[1,2,3,2.5],         ##X is the input 
        [2.0,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]


class layer_dense:
    def __init__(self,n_inputs, n_neurons):
        self.weights=0.10 * np.random.randn(n_inputs, n_neurons)    # matrtix of size  n_inputs * n_neurons 
        self.biases=np.zeros(1,)
    def forward(self,inputs):
        self.output=np.dot(inputs, self.weights) + self.biases

layer1 = layer_dense(4,5)
layer2 =layer_dense(5,2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print('\n',layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]

 [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [36]:
weights=0.10 * np.random.randn(4,3)
print(weights)  

[[ 0.01549474  0.03781625 -0.08877857]
 [-0.19807965 -0.03479121  0.0156349 ]
 [ 0.12302907  0.12023798 -0.03873268]
 [-0.03023028 -0.1048553  -0.14200179]]
